"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import type { Node, Edge } from "@xyflow/react"
import { getValidSession } from "@/lib/auth"

function getApiBaseUrl() {
  const value = process.env.NEXT_PUBLIC_API_BASE_URL
  return value && value.trim().length > 0 ? value.trim() : "http://localhost:8000/api/v1"
}

// ---------------------------------------------------------------------------
// Event types mirroring the backend event_type values
// ---------------------------------------------------------------------------

export type DefinitionEventType =
  | "workflow_created"
  | "node_added"
  | "node_updated"
  | "node_removed"
  | "edge_added"
  | "edge_removed"
  | "variables_updated"
  // Build-mode events (FASE 3)
  | "build_started"
  | "pending_node_added"
  | "pending_edge_added"
  | "pending_node_updated"
  | "pending_node_removed"
  | "pending_edge_removed"
  | "build_ready"
  | "build_confirmed"
  | "build_cancelled"

export interface DefinitionEvent {
  seq: number
  event_id: string
  workflow_id: string
  event_type: DefinitionEventType
  payload: Record<string, unknown>
  client_mutation_id: string | null
  ts: string
}

// ---------------------------------------------------------------------------
// Connection status
// ---------------------------------------------------------------------------

export type StreamStatus = "connecting" | "connected" | "reconnecting" | "error"

// ---------------------------------------------------------------------------
// Build mode event callback
// ---------------------------------------------------------------------------

export interface BuildModeHandlers {
  onBuildStarted: (sessionId: string, reason: string) => void
  onPendingNodeAdded: (node: Record<string, unknown>) => void
  onPendingEdgeAdded: (edge: Record<string, unknown>) => void
  onPendingNodeUpdated: (nodeId: string, dataPatch: Record<string, unknown>) => void
  onPendingNodeRemoved: (nodeId: string) => void
  onPendingEdgeRemoved: (edgeId: string) => void
  onBuildReady: () => void
  onBuildConfirmed: (pendingNodes: Node[], pendingEdges: Edge[]) => void
  onBuildCancelled: () => void
  /** Called when no SSE event arrives for 15s while in build mode — caller should cancel. */
  onSseDropDetected?: () => void
}

// ---------------------------------------------------------------------------
// Idempotent apply helpers
// ---------------------------------------------------------------------------

function applyNodeAdded(nodes: Node[], payload: Record<string, unknown>): Node[] {
  const nodeId = payload.node_id as string
  if (nodes.some((n) => n.id === nodeId)) return nodes
  const newNode: Node = {
    id: nodeId,
    type: payload.node_type as string,
    position: payload.position as { x: number; y: number },
    data: (payload.data as Record<string, unknown>) ?? {},
  }
  return [...nodes, newNode]
}

function applyNodeUpdated(nodes: Node[], payload: Record<string, unknown>): Node[] {
  const nodeId = payload.node_id as string
  return nodes.map((n) =>
    n.id === nodeId ? { ...n, data: { ...n.data, ...(payload.data as Record<string, unknown>) } } : n,
  )
}

function applyEdgeAdded(edges: Edge[], payload: Record<string, unknown>): Edge[] {
  const edgeId = payload.edge_id as string
  if (edges.some((e) => e.id === edgeId)) return edges
  const newEdge: Edge = {
    id: edgeId,
    source: payload.source as string,
    target: payload.target as string,
    sourceHandle: (payload.sourceHandle as string) ?? null,
    targetHandle: (payload.targetHandle as string) ?? null,
    style: { strokeWidth: 2 },
    animated: true,
  }
  return [...edges, newEdge]
}

function applyEdgeRemoved(edges: Edge[], payload: Record<string, unknown>): Edge[] {
  const edgeId = payload.edge_id as string
  return edges.filter((e) => e.id !== edgeId)
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

interface UseWorkflowDefinitionStreamOptions {
  workflowId: string
  enabled: boolean
  setNodes: (updater: (nodes: Node[]) => Node[]) => void
  setEdges: (updater: (edges: Edge[]) => Edge[]) => void
  setVariables?: (vars: unknown[]) => void
  /** Tracks the last seq seen — pass a ref or state setter from the parent. */
  onSeqUpdate?: (seq: number) => void
  /** Set of clientMutationIds generated by this browser session — used for echo prevention. */
  localMutationIds?: React.MutableRefObject<Set<string>>
  /** Handlers for build-mode SSE events. When provided, build mode events are dispatched. */
  buildModeHandlers?: BuildModeHandlers
  /** Current pending nodes — needed for build_confirmed promotion */
  pendingNodesRef?: React.MutableRefObject<Node[]>
  /** Current pending edges — needed for build_confirmed promotion */
  pendingEdgesRef?: React.MutableRefObject<Edge[]>
  /** When true, a 15s idle timer fires onSseDropDetected if no events arrive. */
  buildModeActive?: boolean
}

export interface UseWorkflowDefinitionStreamResult {
  status: StreamStatus
  /** Registers a client mutation ID for echo prevention. Auto-expires after 60s. */
  registerLocalMutation: (id: string) => void
}

export function useWorkflowDefinitionStream({
  workflowId,
  enabled,
  setNodes,
  setEdges,
  setVariables,
  onSeqUpdate,
  localMutationIds,
  buildModeHandlers,
  pendingNodesRef,
  pendingEdgesRef,
  buildModeActive,
}: UseWorkflowDefinitionStreamOptions): UseWorkflowDefinitionStreamResult {
  const [status, setStatus] = useState<StreamStatus>("connecting")
  const lastSeqRef = useRef<number>(0)
  const abortRef = useRef<AbortController | null>(null)
  const retryCountRef = useRef(0)
  const retryTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const dropTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  // Reset the 15s drop-detection timer whenever an event arrives during build mode.
  const resetDropTimer = useCallback(() => {
    if (!buildModeActive || !buildModeHandlers?.onSseDropDetected) return
    if (dropTimerRef.current) clearTimeout(dropTimerRef.current)
    dropTimerRef.current = setTimeout(() => {
      buildModeHandlers?.onSseDropDetected?.()
    }, 15_000)
  }, [buildModeActive, buildModeHandlers])

  // Start/stop drop timer based on build mode activation.
  useEffect(() => {
    if (buildModeActive) {
      resetDropTimer()
    } else {
      if (dropTimerRef.current) clearTimeout(dropTimerRef.current)
    }
    return () => {
      if (dropTimerRef.current) clearTimeout(dropTimerRef.current)
    }
  }, [buildModeActive, resetDropTimer])

  const applyEvent = useCallback(
    (event: DefinitionEvent) => {
      if (event.seq <= lastSeqRef.current) return
      lastSeqRef.current = event.seq
      onSeqUpdate?.(event.seq)
      resetDropTimer()

      // Echo prevention: skip events this browser tab already applied locally.
      if (event.client_mutation_id && localMutationIds?.current.has(event.client_mutation_id)) {
        localMutationIds.current.delete(event.client_mutation_id)
        return
      }

      switch (event.event_type) {
        // ── Standard definition events (FASE 2) ───────────────────────────
        case "node_added":
          setNodes((prev) => applyNodeAdded(prev, event.payload))
          break
        case "node_updated":
          setNodes((prev) => applyNodeUpdated(prev, event.payload))
          break
        case "node_removed": {
          const nodeId = event.payload.node_id as string
          const removedEdgeIds = new Set((event.payload.removed_edges as string[]) ?? [])
          setNodes((prev) => prev.filter((n) => n.id !== nodeId))
          setEdges((prev) => prev.filter((e) => !removedEdgeIds.has(e.id)))
          break
        }
        case "edge_added":
          setEdges((prev) => applyEdgeAdded(prev, event.payload))
          break
        case "edge_removed":
          setEdges((prev) => applyEdgeRemoved(prev, event.payload))
          break
        case "variables_updated":
          setVariables?.((event.payload.variables as unknown[]) ?? [])
          break

        // ── Build-mode events (FASE 3) ────────────────────────────────────
        case "build_started":
          buildModeHandlers?.onBuildStarted(
            event.payload.session_id as string,
            (event.payload.reason as string) ?? "",
          )
          break
        case "pending_node_added":
          buildModeHandlers?.onPendingNodeAdded(
            event.payload.node as Record<string, unknown>,
          )
          break
        case "pending_edge_added":
          buildModeHandlers?.onPendingEdgeAdded(
            event.payload.edge as Record<string, unknown>,
          )
          break
        case "pending_node_updated":
          buildModeHandlers?.onPendingNodeUpdated(
            event.payload.node_id as string,
            event.payload.data_patch as Record<string, unknown>,
          )
          break
        case "pending_node_removed":
          buildModeHandlers?.onPendingNodeRemoved(event.payload.node_id as string)
          break
        case "pending_edge_removed":
          buildModeHandlers?.onPendingEdgeRemoved(event.payload.edge_id as string)
          break
        case "build_ready":
          buildModeHandlers?.onBuildReady()
          break
        case "build_confirmed":
          // Promote ghost nodes/edges to real ones (strip __pending flag)
          buildModeHandlers?.onBuildConfirmed(
            pendingNodesRef?.current ?? [],
            pendingEdgesRef?.current ?? [],
          )
          break
        case "build_cancelled":
          buildModeHandlers?.onBuildCancelled()
          break

        default:
          break
      }
    },
    [setNodes, setEdges, setVariables, onSeqUpdate, localMutationIds, buildModeHandlers, pendingNodesRef, pendingEdgesRef, resetDropTimer],
  )

  const connect = useCallback(async () => {
    if (!enabled || workflowId === "new") return

    abortRef.current?.abort()
    const controller = new AbortController()
    abortRef.current = controller

    setStatus(retryCountRef.current === 0 ? "connecting" : "reconnecting")

    try {
      const session = await getValidSession()
      if (!session || controller.signal.aborted) return

      const since = lastSeqRef.current > 0 ? `?since=${lastSeqRef.current}` : ""
      const url = `${getApiBaseUrl()}/workflows/${workflowId}/definition/events${since}`

      const response = await fetch(url, {
        headers: {
          Accept: "text/event-stream",
          Authorization: `Bearer ${session.accessToken}`,
        },
        signal: controller.signal,
      })

      if (!response.ok || !response.body) {
        throw new Error(`SSE HTTP ${response.status}`)
      }

      setStatus("connected")
      retryCountRef.current = 0

      const reader = response.body.getReader()
      const decoder = new TextDecoder()
      let buffer = ""

      while (true) {
        if (controller.signal.aborted) {
          await reader.cancel()
          break
        }
        const { done, value } = await reader.read()
        if (done) break

        buffer += decoder.decode(value, { stream: true })
        const parts = buffer.split("\n\n")
        buffer = parts.pop() ?? ""

        for (const part of parts) {
          if (!part.trim() || part.startsWith(":")) continue
          const lines = part.split("\n")
          let eventType = ""
          let dataRaw = ""
          for (const line of lines) {
            if (line.startsWith("event:")) eventType = line.slice(6).trim()
            else if (line.startsWith("data:")) dataRaw = line.slice(5).trim()
          }
          if (!eventType || !dataRaw) continue
          try {
            const parsed = JSON.parse(dataRaw) as DefinitionEvent
            applyEvent({ ...parsed, event_type: eventType as DefinitionEventType })
          } catch {
            // malformed frame — skip
          }
        }
      }
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") return
      setStatus("error")
    }

    // Reconnect with exponential back-off + jitter (max 30 s) unless deliberately aborted.
    if (!controller.signal.aborted) {
      const delay = Math.min(1000 * 2 ** retryCountRef.current, 30_000) + Math.random() * 1000
      retryCountRef.current += 1
      setStatus("reconnecting")
      retryTimerRef.current = setTimeout(() => void connect(), delay)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [workflowId, enabled, applyEvent])

  useEffect(() => {
    if (!enabled || workflowId === "new") {
      setStatus("connecting")
      return
    }
    retryCountRef.current = 0
    void connect()

    return () => {
      abortRef.current?.abort()
      if (retryTimerRef.current) clearTimeout(retryTimerRef.current)
    }
  }, [workflowId, enabled, connect])

  const registerLocalMutation = useCallback(
    (id: string) => {
      if (!localMutationIds) return
      localMutationIds.current.add(id)
      // TTL: remove after 60s in case the echo event never arrives
      setTimeout(() => {
        localMutationIds.current.delete(id)
      }, 60_000)
    },
    [localMutationIds],
  )

  return { status, registerLocalMutation }
}
